### ISSUE TITLE
Clone some utility methods from Jezza

### ISSUE THREAD

**Issue by NPException42** [NPException42/NPArcade#10]
https://github.com/Jezzadabomb338/Elemental-Sciences-2/blob/master/es_common/me/jezzadabomb/es2/client/utils/RenderUtils.java#L258

**Comment by Jezza** [comment]
This as now be superseeded by [BlockRenderer](https://github.com/Jezza/OmnisCore/blob/master/common/me/jezza/oc/client/renderer/BlockRenderer.java)

**Comment by NPException42** [comment]
Will rewrite completely from scratch. Will use OC for that.
