### ISSUE TITLE
Game crashes if image in null

### ISSUE THREAD

**Issue by tiffit** [NPException42/NPArcade#10]
The game will crash when you insert a cartridge of a game that returns false on the needsDraw() method on the first frame. 

You get an NPE on [this line](https://github.com/NPException/NPArcade/blob/28f4a119772edda72e77c89f887c776fcafb730e/src/main/java/de/npe/mcmods/nparcade/client/arcade/ArcadeMachine.java#L276).

_[EDIT by NPException: Changed link to point to affected file version]_

**Comment by NPException** [comment]
Feels like odd behaviour that a game does not want to draw at least one frame. But since it should be an easy adjustment to make, I'll just keep the screen black in this case.

**Comment by NPException** [comment]
Though I guess that if a game starts with just a blck background, it's a valid option to not draw anything in that case.

**Comment by NPException** [comment]
Fixed with commit d39dc14fe2d97d06c67ebdafa9ae05db7496806c
