### ISSUE TITLE
[Suggestion] Localization support

### ISSUE THREAD

**Issue by Vexatos** [NPException42/NPArcade#5]
The things added by the mod should be localized. There are not many, but a few is better than nothing. If the mod supported localizations, I'd translate it into the German language.

**Comment by NPException42** [comment]
Lange hat's gedauert.

Ich bin gerade dabei die Mod von Grund auf neu zu schreiben. Lediglich die Models werde ich übernehmen. Sobald ich einen releasefähigen Zustand erreicht habe, werde ich den Code hier auf GitHub in einem neuen Projekt verfügbar machen.

Wenn dann noch Interesse besteht, kannst du gern Pull Requests für die Lokalisierung machen. :D
